import Link from "next/link";
import PublicPage from "../_components/general/public-page";
import { PageSection, Split } from "../_components/programmheft/page-section";
import { Heading } from "../_components/programmheft/section-head";
import { WayList, WayRow } from "../_components/programmheft/way-list";
import { LICENSE_PACKAGES } from "@/lib/licenses.generated";
import { LICENSE_INFO } from "@/lib/license-texts";
import { buildPageMetadata } from "@/lib/seo";

export const metadata = buildPageMetadata({
  title: "Open-Source-Lizenzen",
  description:
    "Die Open-Source-Pakete, die diese Website verwendet, mit ihren Lizenzen im Wortlaut.",
  path: "/lizenzen",
});

/** Fließtext der Seite: Tinte, ruhige Zeilenlänge (Legal Page Rule: 65ch). */
const PROSE =
  "text-ink dark:text-night-text max-w-[65ch] space-y-4 text-lg leading-relaxed";

/** Direct dependencies and their licence texts, generated by scripts/generate-licenses.ts. */
export default function LizenzenPage() {
  // Licences in the order the packages introduce them, so the texts below
  // follow the same reading order as the list above.
  const licenses = [...new Set(LICENSE_PACKAGES.map((pkg) => pkg.license))];

  return (
    <PublicPage
      title="Open-Source-Lizenzen"
      breadcrumbs={[
        { label: "Start", href: "/" },
        { label: "Impressum", href: "/impressum" },
        { label: "Open-Source-Lizenzen" },
      ]}
      description={
        <p>
          Diese Website nutzt die folgenden Open-Source-Pakete. Vielen Dank an
          alle, die daran arbeiten.
        </p>
      }
    >
      <PageSection labelledBy="pakete-heading">
        <Split
          head={<Heading id="pakete-heading">Verwendete Pakete</Heading>}
          bodyClassName="mt-8"
        >
          <WayList labelledBy="pakete-heading">
            {LICENSE_PACKAGES.map((pkg) => {
              const meta = [pkg.versions.join(", "), pkg.license, pkg.copyright]
                .filter(Boolean)
                .join(" · ");
              return (
                <WayRow
                  key={pkg.name}
                  href={pkg.homepage ?? undefined}
                  title={pkg.name}
                  description={meta}
                />
              );
            })}
          </WayList>

          <p className="text-dark dark:text-night-muted mt-6 max-w-[65ch] text-sm leading-relaxed">
            Die Liste wird bei jedem Build automatisch aus den tatsächlich
            eingebundenen Abhängigkeiten erzeugt. Nicht aufgeführt sind Pakete,
            die von den genannten ihrerseits mitgebracht werden, sowie
            Werkzeuge, die nur bei der Entwicklung laufen.
          </p>
        </Split>
      </PageSection>

      <PageSection labelledBy="wortlaut-heading" rule>
        <Split
          head={
            <Heading id="wortlaut-heading" className="text-balance">
              Die Lizenzen im Wortlaut
            </Heading>
          }
          bodyClassName="mt-8 space-y-12"
        >
          {licenses.map((license) => {
            const info = LICENSE_INFO[license];
            const users = LICENSE_PACKAGES.filter(
              (pkg) => pkg.license === license,
            ).map((pkg) => pkg.name);

            return (
              <div key={license}>
                <Heading as="h3" size="list" rule>
                  {info?.title ?? license}
                </Heading>

                <div className={`${PROSE} mt-5`}>
                  {info ? (
                    <>
                      <p>{info.summary}</p>
                      {info.note && <p>{info.note}</p>}
                    </>
                  ) : (
                    <p>
                      Der Lizenztext ist über die Projektseiten der unten
                      genannten Pakete abrufbar.
                    </p>
                  )}
                </div>

                <p className="text-dark dark:text-night-muted mt-3 text-sm">
                  <span className="font-semibold">Verwendet von:</span>{" "}
                  {users.join(", ")}
                </p>

                {info && (
                  <pre className="border-rule dark:border-night-rule text-ink dark:text-night-text mt-4 overflow-x-auto border-t pt-4 text-xs leading-relaxed whitespace-pre-wrap">
                    {info.text}
                  </pre>
                )}
              </div>
            );
          })}
        </Split>
      </PageSection>

      <PageSection labelledBy="hinweise-heading" rule>
        <Split
          head={<Heading id="hinweise-heading">Weitere Hinweise</Heading>}
          bodyClassName="mt-8"
        >
          <div className={PROSE}>
            <p>
              Die Notendarstellung in unseren Übungsspielen nutzt die Schriftart{" "}
              <a
                href="https://github.com/steinbergmedia/bravura"
                target="_blank"
                rel="noopener noreferrer"
                className="link-ink"
              >
                Bravura
                <span className="sr-only"> (öffnet eine externe Website)</span>
              </a>{" "}
              von Steinberg Media Technologies unter der SIL Open Font License
              1.1.
            </p>
            <p>
              Anbieterkennzeichnung und Haftungshinweise findest du im{" "}
              <Link href="/impressum" className="link-ink">
                Impressum
              </Link>
              .
            </p>
          </div>
        </Split>
      </PageSection>
    </PublicPage>
  );
}
