export const coursesData = [
  {
    title: "Bläser-, Familien-, Skifreizeit",
    description:
      "Lust auf einen ganz besonderen, stimmungsvollen Jahreswechsel? Darüber hinaus Spaß am Wintersport und am Blechblasen (zumindest einer in der Familie!)? Dann sind die Tage auf dem Paulinghof in Österreich nicht zu toppen.",
    startDate: "2025-12-28T13:00:00.000Z",
    endDate: "2026-01-05T09:00:00.000Z",
    locationVenue: "Paulinghof",
    locationCity: "Breitenbach am Inn, Österreich",
    courseType: "FREIZEIT",
    targetAudience: "ALLE",
    registrationOpen: true,
    registrationDeadline: "2025-10-31T23:59:59.000Z",
    maxParticipants: 60,
    allowWaitingList: true,
    priceOptions: [
      {
        price: 490,
        label: "Erwachsene",
        maxParticipants: 30,
      },
      {
        price: 330,
        label: "Kinder und Jugendliche",
        maxParticipants: 30,
      },
    ],
    isFree: false,
    prerequisites:
      "Für die Teilnahme muss ein Mitglied der Familie ein Instrument spielen können.",
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2025-01-10T10:00:00.000Z",
  },
  {
    title: "Komponistenportrait: Simon Langenbach",
    description:
      "Simon Langenbach ist ein aufstrebender Komponist und Arrangeur, der sich auf zeitgenössische Bläsermusik spezialisiert hat. In diesem Kurs werden wir seine Werke kennenlernen, analysieren und gemeinsam musizieren.",
    startDate: "2026-01-31T09:00:00.000Z",
    endDate: "2026-01-31T17:00:00.000Z",
    locationVenue: "Historischer Gemeindesaal",
    locationCity: "Bad Godesberg",
    courseType: "KOMPONISTENPORTRAIT",
    priceOptions: [
      {
        price: 25,
        label: "Standardpreis",
        maxParticipants: 100,
      },
    ],
    maxParticipants: 100,
    allowWaitingList: false,
    targetAudience: "ALLE",
    registrationOpen: true,
    registrationDeadline: "2026-01-16T22:59:59.000Z",
    isFree: false,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2025-11-15T10:00:00.000Z",
  },
  {
    title: "Lehrgang für Posaunenchorleitung",
    description:
      "Der Kurs ist ein Angebot für gestandene Chorleiterinnen und Chorleiter, die Interesse haben, ihr Wissen rund um die Chorleitung aufzufrischen und neben der Kontaktpflege neue Literatur kennen zu lernen. Darüber hinaus ist der Kurs auf Bläserinnen und Bläser zugeschnitten, die Interesse an der Chorleitung haben und in drei aufeinander aufbauenden Lehrgängen den Befähigungsnachweis anstreben.",
    startDate: "2026-02-19T17:00:00.000Z",
    endDate: "2026-02-22T13:00:00.000Z",
    locationVenue: "Haus Marienhof",
    locationStreet: "Königswinterer Str. 414",
    locationCity: "Königswinter",
    courseType: "LEHRGANG",
    priceOptions: [
      {
        price: 320,
        label: "Doppelzimmer",
        description: "Übernachtung im Doppelzimmer mit Vollpension",
        maxParticipants: 60,
      },
      {
        price: 360,
        label: "Einzelzimmer",
        description: "Übernachtung im Einzelzimmer mit Vollpension",
        maxParticipants: 40,
      },
    ],
    maxParticipants: 100,
    allowWaitingList: false,
    targetAudience: "DIRIGENTEN",
    registrationOpen: true,
    registrationDeadline: "2026-01-16T22:59:59.000Z",
    isFree: false,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2025-11-15T10:00:00.000Z",
  },
  {
    title: "Lehrgang für Jungbläser*innen",
    description:
      "Eingeladen sind sowohl Anfänger mit Grundkenntnissen, als auch fortgeschrittene jugendliche Bläserinnen und Bläser. Mit einem bewährten Mitarbeiterteam werden wir in verschiedenen Leistungsgruppen differenzieren, um den unterschiedlichen Voraussetzungen gerecht zu werden.",
    startDate: "2026-03-30T14:00:00.000Z",
    endDate: "2026-04-03T13:00:00.000Z",
    locationVenue: "Ebernburg",
    locationStreet: "Burgstraße 38",
    locationCity: "Bad Münster am Stein Ebernburg",
    courseType: "LEHRGANG",
    priceOptions: [
      {
        price: 255,
        label: "Kinder / Jugendliche im Doppelzimmer",
        maxParticipants: 150,
      },
      {
        price: 325,
        label: "Erwachsene im Doppelzimmer",
        maxParticipants: 100,
      },
      {
        price: 380,
        label: "Erwachsene im Einzelzimmer",
        maxParticipants: 50,
      },
    ],
    maxParticipants: 300,
    allowWaitingList: false,
    targetAudience: "ANFAENGER",
    registrationOpen: true,
    registrationDeadline: "2026-01-31T22:59:59.000Z",
    isFree: false,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2025-11-15T10:00:00.000Z",
  },
  {
    title: "Lehrgang für fortgeschrittene Bläser*innen",
    description:
      "Zu diesem Lehrgang sind Bläserinnen und Bläser (ab 16 Jahre) eingeladen, die über eine mehrjährige Posaunenchorerfahrung verfügen, sicher im Choralspiel sind, das gängige Choralvorspielmaterial kennen und solide im Vom-Blatt-Spiel sind.",
    startDate: "2026-04-07T14:00:00.000Z",
    endDate: "2026-04-12T13:00:00.000Z",
    locationVenue: "Ebernburg",
    locationStreet: "Burgstraße 38",
    locationCity: "Bad Münster am Stein Ebernburg",
    courseType: "LEHRGANG",
    priceOptions: [
      {
        price: 370,
        label: "Doppelzimmer",
        description: "Übernachtung im Doppelzimmer mit Vollpension",
        maxParticipants: 40,
      },
      {
        price: 455,
        label: "Einzelzimmer",
        description: "Übernachtung im Einzelzimmer mit Vollpension",
        maxParticipants: 20,
      },
    ],
    maxParticipants: 60,
    allowWaitingList: false,
    targetAudience: "FORTGESCHRITTENE",
    registrationOpen: true,
    registrationDeadline: "2026-01-31T22:59:59.000Z",
    isFree: false,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2025-11-15T10:00:00.000Z",
  },
];
