export const ensemblesData = [
  // Bezirk 1 - Unterer Niederrhein
  {
    name: "Posaunenchor Moers-Zentrum",
    description:
      "Traditioneller Posaunenchor mit über 30 aktiven Bläserinnen und Bläsern",
    bezirk: 1,
    locationName: "Gemeindehaus Moers-Zentrum",
    rehearsalDay: "Dienstag",
    rehearsalTime: "19:30-21:00",
    contactEmail: "posaunenchor@eg-moers.de",
    contactPhone: "02841 123456",
    isActive: true,
  },
  {
    name: "Jugendposaunenchor Duisburg-Süd",
    description: "Junger und dynamischer Chor für Bläser von 12-25 Jahren",
    bezirk: 1,
    locationName: "Evangelische Kirche Duisburg-Süd",
    rehearsalDay: "Mittwoch",
    rehearsalTime: "18:00-19:30",
    isActive: true,
  },

  // Bezirk 2 - Rhein-Lippe
  {
    name: "Posaunenchor Dinslaken",
    description: "Evangelischer Posaunenchor mit langer Tradition",
    bezirk: 2,
    locationName: "Gemeindehaus Dinslaken",
    rehearsalDay: "Montag",
    rehearsalTime: "19:30-21:00",
    contactEmail: "info@posaunenchor-dinslaken.de",
    contactWebsite: "https://posaunenchor-dinslaken.de",
    isActive: true,
  },
  {
    name: "Bläserkreis Wesel",
    description: "Überregionaler Bläserkreis mit monatlichen Proben",
    bezirk: 2,
    rehearsalDay: "Erster Samstag im Monat",
    rehearsalTime: "15:00-18:00",
    isActive: true,
  },

  // Bezirk 3 - Essen-Mülheim
  {
    name: "Bezirksposaunenchor Essen-Mülheim",
    description:
      "Der Bezirksposaunenchor vereint Bläserinnen und Bläser aus dem gesamten Bezirk",
    bezirk: 3,
    locationName: "Pauluskirche Essen",
    rehearsalDay: "Donnerstag",
    rehearsalTime: "19:30-21:30",
    contactEmail: "bezirkspc@essen-muelheim.de",
    isActive: true,
  },
  {
    name: "Posaunenchor Essen-Werden",
    description: "Posaunenchor der evangelischen Kirchengemeinde Werden",
    bezirk: 3,
    locationName: "Gemeindehaus Essen-Werden",
    rehearsalDay: "Dienstag",
    rehearsalTime: "20:00-21:30",
    contactEmail: "posaunenchor@werden-evangelisch.de",
    isActive: true,
  },
  {
    name: "Jugendposaunenchor Mülheim",
    description: "Für junge Bläser mit Freude an moderner Musik",
    bezirk: 3,
    locationName: "Johanneskirche Mülheim",
    rehearsalDay: "Freitag",
    rehearsalTime: "18:00-19:30",
    isActive: true,
  },

  // Bezirk 4 - Düsseldorf-Krefeld-Niederberg
  {
    name: "Posaunenchor Düsseldorf-Oberkassel",
    description:
      "Aktiver Posaunenchor mit regelmäßigen Auftritten in Gottesdiensten",
    bezirk: 4,
    locationName: "Gemeindezentrum Oberkassel",
    rehearsalDay: "Mittwoch",
    rehearsalTime: "19:30-21:00",
    contactEmail: "pc@oberkassel-evangelisch.de",
    isActive: true,
  },
  {
    name: "Posaunenchor Krefeld-Süd",
    description: "Gemeindeposaunenchor mit 25 Mitgliedern",
    bezirk: 4,
    locationName: "Martin-Luther-Kirche Krefeld",
    rehearsalDay: "Montag",
    rehearsalTime: "19:30-21:00",
    isActive: true,
  },
  {
    name: "Bläserensemble Niederberg",
    description: "Kammermusikalisches Ensemble für anspruchsvolle Literatur",
    bezirk: 4,
    locationName: "Gemeindehaus Niederberg",
    rehearsalDay: "Dienstag",
    rehearsalTime: "20:00-22:00",
    contactEmail: "info@blaesersemble-niederberg.de",
    isActive: true,
  },

  // Bezirk 5 - Bergisches Land
  {
    name: "Posaunenchor Wermelskirchen",
    description: "Einer der größten Posaunenchöre im Bergischen Land",
    bezirk: 5,
    locationName: "Gemeindezentrum Wermelskirchen",
    rehearsalDay: "Donnerstag",
    rehearsalTime: "19:30-21:00",
    contactEmail: "posaunenchor@wermelskirchen-evangelisch.de",
    contactWebsite: "https://pc-wermelskirchen.de",
    isActive: true,
  },
  {
    name: "Posaunenchor Remscheid-Lennep",
    description: "Traditionschor seit 1898",
    bezirk: 5,
    locationName: "Dietrich-Bonhoeffer-Kirche Remscheid",
    rehearsalDay: "Dienstag",
    rehearsalTime: "19:30-21:00",
    isActive: true,
  },
  {
    name: "Jugendposaunenchor Bergisch Gladbach",
    description: "Jugendchor mit Schwerpunkt auf moderner Kirchenmusik",
    bezirk: 5,
    locationName: "Christuskirche Bergisch Gladbach",
    rehearsalDay: "Mittwoch",
    rehearsalTime: "18:00-19:30",
    isActive: true,
  },

  // Bezirk 6 - Köln
  {
    name: "Posaunenchor Köln-Deutz",
    description: "Großer Posaunenchor mit über 40 aktiven Mitgliedern",
    bezirk: 6,
    locationName: "Gemeindehaus Köln-Deutz",
    rehearsalDay: "Montag",
    rehearsalTime: "19:30-21:00",
    contactEmail: "info@pc-deutz.de",
    contactPhone: "0221 987654",
    contactWebsite: "https://pc-deutz.de",
    isActive: true,
  },
  {
    name: "Posaunenchor Köln-Mülheim",
    description: "Vielseitiger Chor für Gottesdienste und Konzerte",
    bezirk: 6,
    locationName: "Kartäuserkirche Köln",
    rehearsalDay: "Donnerstag",
    rehearsalTime: "19:30-21:00",
    isActive: true,
  },
  {
    name: "Bläserkreis Köln-Süd",
    description: "Bezirksübergreifender Bläserkreis",
    bezirk: 6,
    locationName: "Melanchthon-Akademie Köln",
    rehearsalDay: "Zweiter Samstag im Monat",
    rehearsalTime: "14:00-17:00",
    contactEmail: "blaeserskreis@koeln-sued.de",
    isActive: true,
  },

  // Bezirk 7 - Aachen-Jülich
  {
    name: "Posaunenchor Aachen-Burtscheid",
    description: "Posaunenchor der Evangelischen Gemeinde Burtscheid",
    bezirk: 7,
    locationName: "Gemeindehaus Aachen-Burtscheid",
    rehearsalDay: "Mittwoch",
    rehearsalTime: "19:30-21:00",
    contactEmail: "posaunenchor@burtscheid.de",
    isActive: true,
  },
  {
    name: "Posaunenchor Jülich",
    description: "Aktiver Chor mit Schwerpunkt Gemeindearbeit",
    bezirk: 7,
    locationName: "Christuskirche Jülich",
    rehearsalDay: "Dienstag",
    rehearsalTime: "19:30-21:00",
    isActive: true,
  },

  // Bezirk 8 - Bonn
  {
    name: "Posaunenchor Bonn-Beuel",
    description: "Einer der ältesten Posaunenchöre in Bonn",
    bezirk: 8,
    locationName: "Gemeindehaus Beuel",
    rehearsalDay: "Montag",
    rehearsalTime: "19:30-21:00",
    contactEmail: "pc@beuel-evangelisch.de",
    isActive: true,
  },
  {
    name: "Posaunenchor Bad Godesberg",
    description: "Traditionsreicher Chor mit vielfältigem Repertoire",
    bezirk: 8,
    locationName: "Erlöserkirche Bad Godesberg",
    rehearsalDay: "Donnerstag",
    rehearsalTime: "19:30-21:00",
    contactEmail: "info@pc-godesberg.de",
    contactWebsite: "https://pc-godesberg.de",
    isActive: true,
  },
  {
    name: "Jugendposaunenchor Bonn",
    description: "Bezirksjugendposaunenchor für junge Talente",
    bezirk: 8,
    locationName: "Kreuzkirche Bonn",
    rehearsalDay: "Freitag",
    rehearsalTime: "18:00-19:30",
    isActive: true,
  },

  // Bezirk 9 - Oberbergisches Land
  {
    name: "Posaunenchor Gummersbach",
    description: "Großer Gemeindeposaunenchor",
    bezirk: 9,
    locationName: "Evangelische Kirche Gummersbach",
    rehearsalDay: "Dienstag",
    rehearsalTime: "19:30-21:00",
    contactEmail: "posaunenchor@gummersbach-evangelisch.de",
    isActive: true,
  },
  {
    name: "Posaunenchor Waldbröl",
    description: "Aktiver Chor mit regelmäßigen Auftritten",
    bezirk: 9,
    locationName: "Gemeindehaus Waldbröl",
    rehearsalDay: "Mittwoch",
    rehearsalTime: "19:30-21:00",
    isActive: true,
  },

  // Bezirk 10 - Wied
  {
    name: "Posaunenchor Neuwied",
    description: "Posaunenchor der Evangelischen Kirchengemeinde Neuwied",
    bezirk: 10,
    locationName: "Marktkirche Neuwied",
    rehearsalDay: "Donnerstag",
    rehearsalTime: "19:30-21:00",
    contactEmail: "pc@neuwied-evangelisch.de",
    isActive: true,
  },
  {
    name: "Bläserkreis Wied",
    description: "Bezirksbläserkreis mit monatlichen Treffen",
    bezirk: 10,
    rehearsalDay: "Letzter Freitag im Monat",
    rehearsalTime: "19:00-21:30",
    isActive: true,
  },

  // Bezirk 11 - An Nahe und Glan
  {
    name: "Posaunenchor Idar-Oberstein",
    description: "Traditionsreicher Chor im Hunsrück",
    bezirk: 11,
    locationName: "Felsenkirche Idar-Oberstein",
    rehearsalDay: "Mittwoch",
    rehearsalTime: "19:30-21:00",
    contactEmail: "posaunenchor@idar-oberstein.de",
    isActive: true,
  },
  {
    name: "Posaunenchor Kirn",
    description: "Kleiner aber aktiver Gemeindeposaunenchor",
    bezirk: 11,
    locationName: "Pauluskirche Kirn",
    rehearsalDay: "Dienstag",
    rehearsalTime: "19:30-21:00",
    isActive: true,
  },

  // Bezirk 12 - Saarland
  {
    name: "Posaunenchor Saarbrücken",
    description: "Größter Posaunenchor im Saarland",
    bezirk: 12,
    locationName: "Friedenskirche Saarbrücken",
    rehearsalDay: "Montag",
    rehearsalTime: "19:30-21:00",
    contactEmail: "info@pc-saarbruecken.de",
    contactWebsite: "https://pc-saarbruecken.de",
    isActive: true,
  },
  {
    name: "Posaunenchor Homburg",
    description: "Aktiver Gemeindeposaunenchor",
    bezirk: 12,
    locationName: "Erlöserkirche Homburg",
    rehearsalDay: "Donnerstag",
    rehearsalTime: "19:30-21:00",
    contactEmail: "posaunenchor@homburg-evangelisch.de",
    isActive: true,
  },
  {
    name: "Jugendposaunenchor Saarland",
    description: "Landesjugendposaunenchor mit vierteljährlichen Proben",
    bezirk: 12,
    rehearsalDay: "Vierteljährlich samstags",
    rehearsalTime: "10:00-16:00",
    isActive: true,
  },

  // Bezirk 13 - An Sieg und Rhein
  {
    name: "Posaunenchor Siegburg",
    description: "Vielseitiger Posaunenchor mit breitem Repertoire",
    bezirk: 13,
    locationName: "Lutherkirche Siegburg",
    rehearsalDay: "Dienstag",
    rehearsalTime: "19:30-21:00",
    contactEmail: "pc@siegburg-evangelisch.de",
    isActive: true,
  },
  {
    name: "Posaunenchor Troisdorf",
    description: "Gemeindeposaunenchor mit 20 aktiven Mitgliedern",
    bezirk: 13,
    locationName: "Friedenskirche Troisdorf",
    rehearsalDay: "Mittwoch",
    rehearsalTime: "19:30-21:00",
    isActive: true,
  },
  {
    name: "Posaunenchor Königswinter",
    description: "Posaunenchor am Rhein mit Blick auf das Siebengebirge",
    bezirk: 13,
    locationName: "Christuskirche Königswinter",
    rehearsalDay: "Montag",
    rehearsalTime: "19:30-21:00",
    contactEmail: "info@pc-koenigswinter.de",
    isActive: true,
  },
];
