import { EventEnsembleType } from "~/generated/prisma/enums";

export const eventsData = [
  {
    title: "Von Königreichen",
    description: "Festliches Konzert zum Advent",
    eventDate: "2025-11-29T18:30:00.000Z",
    locationVenue: "Evangelische Kirche Hückelhoven",
    locationCity: "Hückelhoven",
    category: "KONZERT",
    performingEnsembleType: EventEnsembleType.AUSWAHLCHOR,
    auswahlChorSlug: "buccinate",
    leitung: "LPW Jörg Häusler",
    isFree: true,
    openToParticipants: false,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2025-11-01T10:00:00.000Z",
  },
  {
    title: "Festliches Adventskonzert",
    description: "mit Werken von Rutter und Pinkham",
    eventDate: "2025-11-30T18:30:00.000Z",
    locationVenue: "Lukaskirche Bonn",
    locationCity: "Bonn",
    category: "KONZERT",
    performingEnsembleType: EventEnsembleType.AUSWAHLCHOR,
    auswahlChorSlug: "buccinate",
    leitung: "Cleve Kersh und LPW Jörg Häusler",
    isFree: true,
    openToParticipants: false,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2025-11-01T10:00:00.000Z",
  },
  {
    title: "Nachweihnachtliche Musik",
    description:
      "Die Nachweihnachtliche Musik im Xantener Dom hat eine große Tradition und trifft auch bei Zuhörenden in der Region auf große Resonanz. Wir laden herzlich zur Mitwirkung ein.",
    eventDate: "2026-01-11T14:30:00.000Z",
    locationVenue: "Dom zu Xanten",
    locationCity: "Xanten",
    category: "KONZERT",
    performingEnsembleType: EventEnsembleType.AUSWAHLCHOR,
    auswahlChorSlug: "conspirito",
    openToParticipants: true,
    participationInfo:
      "Um beim Konzert mitzuwirken, ist die Teilnahme an der Probe am 8. Januar in Duisburg erforderlich. Das Programm und die Noten werden ab dem 1. Dezember zur Verfügung stehen und können bei Jörg Häusler oder Gerald Münster angefordert werden.",
    isFree: true,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2026-01-01T10:00:00.000Z",
  },
  {
    title: "Wie schön leuchtet der Morgenstern",
    eventDate: "2026-01-15T18:30:00.000Z",
    locationVenue: "Trinitatiskirche",
    locationCity: "Köln",
    category: "KONZERT",
    performingEnsembleType: EventEnsembleType.AUSWAHLCHOR,
    auswahlChorSlug: "conspirito",
    openToParticipants: false,
    isFree: true,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2026-01-01T10:00:00.000Z",
  },
  {
    title: "JuPo Konzert",
    eventDate: "2026-03-21T18:00:00.000Z",
    locationVenue: "Abteikirche",
    locationCity: "Otterberg",
    category: "KONZERT",
    performingEnsembleType: EventEnsembleType.AUSWAHLCHOR,
    auswahlChorSlug: "jupo",
    isFree: true,
    openToParticipants: false,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2026-01-01T10:00:00.000Z",
  },
  {
    title: "JuPo Konzert",
    eventDate: "2026-03-22T16:00:00.000Z",
    locationVenue: "Evangelische Kirche Simmern",
    locationCity: "Simmern",
    category: "KONZERT",
    performingEnsembleType: EventEnsembleType.AUSWAHLCHOR,
    auswahlChorSlug: "jupo",
    openToParticipants: false,
    isFree: true,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2026-01-01T10:00:00.000Z",
  },
  {
    title: "JuPo Gottesdienstmitgestaltung",
    eventDate: "2026-05-17T13:00:00.000Z",
    locationCity: "Siegburg",
    category: "GOTTESDIENST",
    performingEnsembleType: EventEnsembleType.AUSWAHLCHOR,
    auswahlChorSlug: "jupo",
    openToParticipants: false,
    isFree: true,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2026-01-01T10:00:00.000Z",
  },
  {
    title: "Christmas Carol Singing",
    eventDate: "2025-11-30T13:30:00.000Z",
    locationVenue: "Altenberger Dom",
    locationCity: "Odenthal",
    category: "KONZERT",
    performingensembleType: EventEnsembleType.CUSTOM,
    performingEnsembleName: "Blechbläser des Posaunenwerks",
    leitung: "LPW Jörg Häusler",
    isFree: true,
    openToParticipants: false,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2025-11-01T10:00:00.000Z",
  },
  {
    title: "Davon ich singen und sagen will",
    description: "Vorweihnachtliches Konzert für Blechbläser und Orgel",
    eventDate: "2025-12-14T17:00:00.000Z",
    locationVenue: "Versöhnungskirche",
    locationCity: "Kleve",
    category: "KONZERT",
    performingensembleType: EventEnsembleType.CUSTOM,
    performingEnsembleName: "KMD Michael Porr, Orgel",
    leitung: "LPW Jörg Häusler",
    isFree: true,
    openToParticipants: false,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2025-11-01T10:00:00.000Z",
  },
  {
    title: "Weihnachtskonzert",
    description: "Vorweihnachtliches Konzert für Blechbläser und Orgel",
    eventDate: "2025-12-21T17:00:00.000Z",
    locationVenue: "Evangelische Kirche",
    locationCity: "Kettwig",
    category: "KONZERT",
    performingensembleType: EventEnsembleType.CUSTOM,
    performingEnsembleName: "Ensemble 23*12 feat. Jens Uhlenhoff",
    leitung: "LPW Jörg Häusler",
    isFree: true,
    openToParticipants: false,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2025-11-01T10:00:00.000Z",
  },
  {
    title: "Probe zur Nachweihnachtlichen Musik",
    description:
      "Die Nachweihnachtliche Musik im Xantener Dom hat eine große Tradition und trifft auch bei Zuhörenden in der Region auf große Resonanz. Wir laden herzlich zur Mitwirkung ein.",
    eventDate: "2026-01-08T18:30:00.000Z",
    locationVenue: "Evangelische Kreuzkirche",
    locationStreet: "In den Bänden 69",
    locationZipCode: "47229",
    locationCity: "Duisburg",
    openToParticipants: true,
    participationInfo:
      "Das Programm und die Noten werden ab dem 1. Dezember zur Verfügung stehen und können bei Jörg Häusler oder Gerald Münster angefordert werden.",
    category: "PROBE",
    isFree: true,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2026-01-01T10:00:00.000Z",
  },
  {
    title: "Adventsblasen im Kölner Dom",
    description:
      "Am Montag nach dem ersten Advent, also am 1. Dezember findet wieder das Adventsblasen unter bewährter Leitung von Gerhard Heywang statt.",
    eventDate: "2025-12-01T18:10:00.000Z",
    locationVenue: "Kölner Dom",
    locationCity: "Köln",
    openToParticipants: true,
    participationInfo:
      "Eine vorherige Probe gibt es nicht. Gespielt werden Adventslieder aus dem Choralbuch und freie Stücke.",
    category: "ANDERE",
    isFree: true,
    status: "APPROVED",
    approved: true,
    pendingReview: false,
    publishedAt: "2026-01-01T10:00:00.000Z",
  },
];
