export const locationsData = [
  // Common venues across different cities
  {
    name: "Gemeindehaus Moers-Zentrum",
    street: "Kirchstraße 12",
    zipCode: "47441",
    city: "Moers",
    additionalInfo: "Eingang über den Kirchhof",
  },
  {
    name: "Evangelische Kirche Duisburg-Süd",
    street: "Koloniestraße 68",
    zipCode: "47057",
    city: "Duisburg",
    additionalInfo: "Proben im Gemeindesaal",
  },
  {
    name: "Gemeindehaus Dinslaken",
    street: "Neustraße 31",
    zipCode: "46535",
    city: "Dinslaken",
  },
  {
    name: "Pauluskirche Essen",
    street: "Pauluskirchstraße 4",
    zipCode: "45130",
    city: "Essen",
    additionalInfo: "Eingang Seitenflügel",
  },
  {
    name: "Gemeindehaus Essen-Werden",
    street: "Heckstraße 40",
    zipCode: "45239",
    city: "Essen",
  },
  {
    name: "Johanneskirche Mülheim",
    street: "Hingbergstraße 176",
    zipCode: "45470",
    city: "Mülheim an der Ruhr",
  },
  {
    name: "Gemeindezentrum Oberkassel",
    street: "Luegallee 121",
    zipCode: "40545",
    city: "Düsseldorf",
    additionalInfo: "Großer Saal im 1. OG",
  },
  {
    name: "Martin-Luther-Kirche Krefeld",
    street: "Martin-Luther-Platz 1",
    zipCode: "47805",
    city: "Krefeld",
  },
  {
    name: "Gemeindehaus Niederberg",
    street: "Kirchplatz 8",
    zipCode: "40878",
    city: "Ratingen",
  },
  {
    name: "Gemeindezentrum Wermelskirchen",
    street: "Telegrafenstraße 15",
    zipCode: "42929",
    city: "Wermelskirchen",
  },
  {
    name: "Dietrich-Bonhoeffer-Kirche Remscheid",
    street: "Konrad-Adenauer-Straße 36",
    zipCode: "42853",
    city: "Remscheid",
  },
  {
    name: "Christuskirche Bergisch Gladbach",
    street: "Hauptstraße 256",
    zipCode: "51465",
    city: "Bergisch Gladbach",
  },
  {
    name: "Kartäuserkirche Köln",
    street: "Kartäusergasse 7",
    zipCode: "50678",
    city: "Köln",
    additionalInfo: "Historisches Kirchengebäude",
  },
  {
    name: "Gemeindehaus Köln-Deutz",
    street: "Tempelstraße 17",
    zipCode: "50679",
    city: "Köln",
  },
  {
    name: "Melanchthon-Akademie Köln",
    street: "Kartäuserwall 24b",
    zipCode: "50678",
    city: "Köln",
    additionalInfo: "Konferenzraum 2. Etage",
  },
  {
    name: "Gemeindehaus Aachen-Burtscheid",
    street: "Jesuitenstraße 9",
    zipCode: "52064",
    city: "Aachen",
  },
  {
    name: "Christuskirche Jülich",
    street: "Düsseldorfer Straße 22",
    zipCode: "52428",
    city: "Jülich",
  },
  {
    name: "Kreuzkirche Bonn",
    street: "Am Hof 2",
    zipCode: "53113",
    city: "Bonn",
    additionalInfo: "Probenraum im Untergeschoss",
  },
  {
    name: "Erlöserkirche Bad Godesberg",
    street: "Koblenzer Straße 39",
    zipCode: "53177",
    city: "Bonn",
  },
  {
    name: "Gemeindehaus Beuel",
    street: "Siegburger Straße 75",
    zipCode: "53229",
    city: "Bonn",
  },
  {
    name: "Evangelische Kirche Gummersbach",
    street: "Kaiserstraße 10",
    zipCode: "51643",
    city: "Gummersbach",
  },
  {
    name: "Gemeindehaus Waldbröl",
    street: "Brölstraße 32",
    zipCode: "51545",
    city: "Waldbröl",
  },
  {
    name: "Marktkirche Neuwied",
    street: "Marktstraße 64",
    zipCode: "56564",
    city: "Neuwied",
  },
  {
    name: "Felsenkirche Idar-Oberstein",
    street: "Am Markt 1",
    zipCode: "55743",
    city: "Idar-Oberstein",
    additionalInfo: "Einzigartige Felsenkirche",
  },
  {
    name: "Pauluskirche Kirn",
    street: "Hauptstraße 89",
    zipCode: "55606",
    city: "Kirn",
  },
  {
    name: "Friedenskirche Saarbrücken",
    street: "Mainzer Straße 47",
    zipCode: "66111",
    city: "Saarbrücken",
    additionalInfo: "Großer Gemeindesaal",
  },
  {
    name: "Erlöserkirche Homburg",
    street: "Zweibrücker Straße 72",
    zipCode: "66424",
    city: "Homburg",
  },
  {
    name: "Lutherkirche Siegburg",
    street: "Luisenstraße 24",
    zipCode: "53721",
    city: "Siegburg",
  },
  {
    name: "Friedenskirche Troisdorf",
    street: "Hippolytusstraße 1",
    zipCode: "53840",
    city: "Troisdorf",
  },
  {
    name: "Christuskirche Königswinter",
    street: "Drachenfelsstraße 5",
    zipCode: "53639",
    city: "Königswinter",
    additionalInfo: "Mit Blick auf das Siebengebirge",
  },
];
