export const registrationsData = [
  // Registration 1 - Family for Ski trip
  {
    courseTitle: "Bläser-, Familien-, Skifreizeit",
    registrantFirstName: "Michael",
    registrantLastName: "Schmidt",
    registrantEmail: "michael.schmidt@example.com",
    registrantPhone: "0221 123456",
    registrantChoir: "Posaunenchor Köln-Deutz",
    registrantDistrict: "Bezirk 6",
    paymentStatus: "PAID",
    registrationStatus: "CONFIRMED",
    participants: [
      {
        firstName: "Michael",
        lastName: "Schmidt",
        birthDate: new Date("1980-05-15"),
        city: "Köln",
        instrument: "Posaune",
        priceOption: "Erwachsene",
      },
      {
        firstName: "Sarah",
        lastName: "Schmidt",
        birthDate: new Date("1982-08-22"),
        city: "Köln",
        instrument: "Querflöte",
        priceOption: "Erwachsene",
      },
      {
        firstName: "Jonas",
        lastName: "Schmidt",
        birthDate: new Date("2010-03-10"),
        city: "Köln",
        instrument: "Trompete",
        priceOption: "Kinder und Jugendliche",
      },
      {
        firstName: "Lena",
        lastName: "Schmidt",
        birthDate: new Date("2012-11-05"),
        city: "Köln",
        instrument: "",
        priceOption: "Kinder und Jugendliche",
      },
    ],
  },
  // Registration 2 - Single person for conductor course
  {
    courseTitle: "Lehrgang für Posaunenchorleitung",
    registrantFirstName: "Thomas",
    registrantLastName: "Weber",
    registrantEmail: "thomas.weber@example.com",
    registrantPhone: "0211 987654",
    registrantChoir: "Posaunenchor Düsseldorf-Oberkassel",
    registrantDistrict: "Bezirk 4",
    paymentStatus: "PENDING",
    registrationStatus: "CONFIRMED",
    participants: [
      {
        firstName: "Thomas",
        lastName: "Weber",
        birthDate: new Date("1975-09-18"),
        city: "Düsseldorf",
        instrument: "Posaune",
        priceOption: "Einzelzimmer",
      },
    ],
  },
  // Registration 3 - Young players course
  {
    courseTitle: "Lehrgang für Jungbläser*innen",
    registrantFirstName: "Petra",
    registrantLastName: "Müller",
    registrantEmail: "petra.mueller@example.com",
    registrantPhone: "0228 456789",
    registrantChoir: "Jugendposaunenchor Bonn",
    registrantDistrict: "Bezirk 8",
    paymentStatus: "PAID",
    registrationStatus: "CONFIRMED",
    participants: [
      {
        firstName: "Anna",
        lastName: "Müller",
        birthDate: new Date("2008-06-12"),
        city: "Bonn",
        instrument: "Trompete",
        priceOption: "Kinder / Jugendliche im Doppelzimmer",
      },
      {
        firstName: "Felix",
        lastName: "Müller",
        birthDate: new Date("2009-02-28"),
        city: "Bonn",
        instrument: "Horn",
        priceOption: "Kinder / Jugendliche im Doppelzimmer",
      },
    ],
  },
  // Registration 4 - Advanced course
  {
    courseTitle: "Lehrgang für fortgeschrittene Bläser*innen",
    registrantFirstName: "Andreas",
    registrantLastName: "Hoffmann",
    registrantEmail: "andreas.hoffmann@example.com",
    registrantPhone: "0201 234567",
    registrantChoir: "Posaunenchor Essen-Werden",
    registrantDistrict: "Bezirk 3",
    paymentStatus: "PAID",
    registrationStatus: "CONFIRMED",
    participants: [
      {
        firstName: "Andreas",
        lastName: "Hoffmann",
        birthDate: new Date("1990-12-03"),
        city: "Essen",
        instrument: "Euphonium",
        priceOption: "Doppelzimmer",
      },
    ],
  },
  // Registration 5 - Composer portrait
  {
    courseTitle: "Komponistenportrait: Simon Langenbach",
    registrantFirstName: "Julia",
    registrantLastName: "Becker",
    registrantEmail: "julia.becker@example.com",
    registrantPhone: "0221 345678",
    registrantChoir: "Posaunenchor Köln-Mülheim",
    registrantDistrict: "Bezirk 6",
    paymentStatus: "PENDING",
    registrationStatus: "CONFIRMED",
    participants: [
      {
        firstName: "Julia",
        lastName: "Becker",
        birthDate: new Date("1988-04-20"),
        city: "Köln",
        instrument: "Tuba",
        priceOption: "Standardpreis",
      },
    ],
  },
  // Registration 6 - Another family for ski trip
  {
    courseTitle: "Bläser-, Familien-, Skifreizeit",
    registrantFirstName: "Frank",
    registrantLastName: "Schneider",
    registrantEmail: "frank.schneider@example.com",
    registrantPhone: "0172 8765432",
    registrantChoir: "Posaunenchor Wermelskirchen",
    registrantDistrict: "Bezirk 5",
    paymentStatus: "PAID",
    registrationStatus: "CONFIRMED",
    participants: [
      {
        firstName: "Frank",
        lastName: "Schneider",
        birthDate: new Date("1985-07-08"),
        city: "Wermelskirchen",
        instrument: "Trompete",
        priceOption: "Erwachsene",
      },
      {
        firstName: "Marie",
        lastName: "Schneider",
        birthDate: new Date("2011-09-14"),
        city: "Wermelskirchen",
        instrument: "Flügelhorn",
        priceOption: "Kinder und Jugendliche",
      },
    ],
  },
];
