export const usersData = [
  // Admin / LPW
  {
    username: "joerg.haeusler",
    email: "joerg.haeusler@posaunenwerk-rheinland.de",
    firstName: "Jörg",
    lastName: "Häusler",
    displayName: "Jörg Häusler",
    role: "LPW",
    bio: "Landesposaunenwart des Posaunenwerks Rheinland. Leiter von Con Spirito, Buccinate Deo und dem Landesjugendposaunenchor.",
    obleuteRole: null,
    obleuteBezirk: null,
  },

  // Regional Posaunenwarte (RPW)
  {
    username: "sonia.singel",
    email: "sonia.singel@posaunenwerk-rheinland.de",
    firstName: "Sonia",
    lastName: "Singel-Römer",
    displayName: "Sonia Singel-Römer",
    role: "RPW",
    displayRole: "Regionalposaunenwartin",
    bio: "Schon früh auf den Instrumenten Flöte, Klavier und Geige ausgebildet, begann Sonia Singel-Roemer im Alter von neun Jahren im Posaunenchor Trompete zu spielen. Später wechselte sie auf Tenorhorn und Posaune, auf der sie schließlich Unterricht bekam. Das Studium der Instrumentalpädagogik (Diplom 1998) und der Orchestermusik (Diplom 2001) mit Hauptfach Posaune an der Folkwang-Hochschule folgten. Während des Studiums erweiterte sie ihre Kenntnisse auf verschiedenen Meisterkursen (bei z.B. Alain Trudel und Michel Becquet). 2004 machte sie die Prüfung zur C-Kirchenmusikerin. Sonia E. Singel-Roemer ist als freiberufliche Posaunistin und Instrumentalpädagogin tätig und lebt mit ihrem Mann und ihren zwei Kindern in Ratingen.",
    obleuteRole: null,
    obleuteBezirk: null,
  },
  {
    username: "matthias.schirg",
    email: "matthias.schirg@posaunenwerk-rheinland.de",
    firstName: "Matthias",
    lastName: "Schirg",
    displayName: "Matthias Schirg",
    role: "RPW",
    displayRole: "Regionalposaunenwart",
    bio: 'Matthias Schirg (*1996) betreut als Regionalposaunenwart den Bezirk 12 (Saar). Aufgewachsen im Saarland führte ihn der musikalische Weg nach den Anfängen in der Musikschule zum Posaunenchor und somit auch zum Posaunenwerk Rheinland. Er ist seit vielen Jahren Mitglied im Landesjugendposaunenchor Rheinland und regelmäßig Mitarbeiter bei verschiedenen Lehrgängen und Freizeiten. Sein Bachelorstudium mit Schwerpunkt „Instrumentalpädagogik" an der Musikhochschule des Saarlandes steht kurz vor dem Abschluss.',
    obleuteRole: null,
    obleuteBezirk: null,
  },
  {
    username: "marion.kutscher",
    email: "marion.kutscher@posaunenwerk-rheinland.de",
    firstName: "Marion",
    lastName: "Kutscher",
    displayName: "Marion Kutscher",
    role: "RPW",
    displayRole: "Regionalposaunenwartin",
    bio: "Marion Kutscher studierte im Hauptfach Trompete sowohl Instrumentalpädagogik in Düsseldorf als auch Orchestermusik in Duisburg. Schon während ihres Studiums spezialisierte sie sich bei Thibaud Robinne auf die Naturtrompete und deren historische Aufführungspraxis. Seitdem spielt sie in verschiedenen Ensembles im In- und Ausland. Hervorzuheben sind besonders Konzerte in Frankreich mit den Sopranistinnen Anne-Sophie von Otter und Cecilia Bartoli mit ihrem Orchester 'Les musiciens du prince'. Neben ihrer Tätigkeit als ausführende Künstlerin leitet sie seit 2010 den Bläserchor der Herrnhuter Brüdergemeine Neuwied und gibt auch Trompetenunterricht.",
    obleuteRole: null,
    obleuteBezirk: null,
  },
  {
    username: "gerald.muenster",
    email: "gerald.muenster@posaunenwerk-rheinland.de",
    firstName: "Gerald",
    lastName: "Münster",
    displayName: "Gerald Münster",
    role: "RPW",
    displayRole: "Regionalposaunenwart",
    bio: 'Gerald Münster, den die meisten nur unter seinem Spitznamen „Gerry" kennen, lebt mit seiner Familie in der Nähe von Duisburg-Friemersheim. Er spielt seit mehr als 40 Jahren Blechblasinstrumente, in erster Linie Trompete. Das eigentliche Hobby wurde mit der Zeit zu seiner persönlichen „Berufung". Als Seiteneinsteiger im Fachbereich Musik arbeitet er eng mit zwei Schulen im Duisburger Raum zusammen. Ein besonderes Anliegen ist die Nachwuchsarbeit, also die Betreuung von Jungbläsern jeden Alters.',
    obleuteRole: null,
    obleuteBezirk: null,
  },
  {
    username: "eike.klein",
    email: "eike.klein@posaunenwerk-rheinland.de",
    firstName: "Eike",
    lastName: "Klein",
    displayName: "Eike Klein",
    role: "RPW",
    displayRole: "Regionalposaunenwart",
    bio: '„Lobet den Herrn mit Posaunen, lobet ihn mit Psalter und Harfe." – Dieses Credo der Posaunenchorarbeit begleitet mich seit frühester Kindheit. Ich studiere Trompete an der Robert Schumann Hochschule in Düsseldorf bei Prof. Peter Mönkediek. Musikalisch groß geworden bin ich in der lippischen Bläserarbeit, wo ich auch meine kirchenmusikalische Ausbildung zum C-Schein absolviert habe. Darüber hinaus leite ich mit viel Freude und Engagement den Posaunenchor Meerbusch-Lank. Posaunenchorarbeit ist für mich das gemeinsame Musizieren von Jung und Alt zum Lobe Gottes und ein lebendiger, freudiger und integrativer Bestandteil der Gemeinschaft.',
    obleuteRole: null,
    obleuteBezirk: null,
  },

  // Bezirksobleute (One per Bezirk)
  {
    username: "doris.haetzel",
    email: "doris.haetzel@posaunenwerk-rheinland.de",
    firstName: "Doris",
    lastName: "Hätzel",
    displayName: "Doris Hätzel",
    role: "OBLEUTE",
    bio: "Bezirksobfrau für den Unteren Niederrhein",
    obleuteRole: "Bezirksobfrau",
    obleuteBezirk: 1, // Bezirk 01 - Unterer Niederrhein
  },
  {
    username: "tim.neuhaus",
    email: "tim.neuhaus@ekir.de",
    firstName: "Tim",
    lastName: "Neuhaus",
    displayName: "Tim Neuhaus",
    role: "OBLEUTE",
    bio: "Bezirksobmann für Rhein-Lippe und Geschäftsführer des Posaunenwerks",
    obleuteRole: "Bezirksobmann",
    obleuteBezirk: 2, // Bezirk 02 - Rhein-Lippe
  },
  {
    username: "dietmar.schruck",
    email: "dietmar.schruck@posaunenwerk-rheinland.de",
    firstName: "Dietmar",
    lastName: "Schruck",
    displayName: "Dietmar Schruck",
    role: "OBLEUTE",
    bio: "Bezirksobmann für Essen-Mülheim",
    obleuteRole: "Bezirksobmann",
    obleuteBezirk: 3, // Bezirk 03 - Essen-Mülheim
  },
  {
    username: "joerg.schroeder",
    email: "joerg.schroeder@posaunenwerk-rheinland.de",
    firstName: "Jörg",
    lastName: "Schröder",
    displayName: "Jörg Schröder",
    role: "OBLEUTE",
    bio: "Bezirksobmann für Düsseldorf-Krefeld-Niederberg",
    obleuteRole: "Bezirksobmann",
    obleuteBezirk: 4, // Bezirk 04 - Düsseldorf-Krefeld-Niederberg
  },
  {
    username: "martin.weidner",
    email: "martin.weidner@posaunenwerk-rheinland.de",
    firstName: "Martin",
    lastName: "Weidner",
    displayName: "Dr. Martin Weidner",
    role: "OBLEUTE",
    bio: "Bezirksobmann für Bergisches Land",
    obleuteRole: "Bezirksobmann",
    obleuteBezirk: 5, // Bezirk 05 - Bergisches Land
  },
  {
    username: "gerhard.heywang",
    email: "gerhard.heywang@posaunenwerk-rheinland.de",
    firstName: "Gerhard",
    lastName: "Heywang",
    displayName: "Dr. Gerhard Heywang",
    role: "OBLEUTE",
    bio: "Bezirksobmann für Köln",
    obleuteRole: "Bezirksobmann",
    obleuteBezirk: 6, // Bezirk 06 - Köln
  },
  {
    username: "birgit.engelmann",
    email: "birgit.engel@posaunenwerk-rheinland.de",
    firstName: "Birgit",
    lastName: "Engelmann",
    displayName: "Birgit Engelmann",
    role: "OBLEUTE",
    bio: "Bezirksobfrau für Aachen-Jülich",
    obleuteRole: "Bezirksobfrau",
    obleuteBezirk: 7, // Bezirk 07 - Aachen-Jülich
  },
  {
    username: "michael.geffert",
    email: "michael.geffert@posaunenwerk-rheinland.de",
    firstName: "Michael",
    lastName: "Geffert",
    displayName: "Dr. Michael Geffert",
    role: "OBLEUTE",
    bio: "Bezirksobmann für Bonn",
    obleuteRole: "Bezirksobmann",
    obleuteBezirk: 8, // Bezirk 08 - Bonn
  },
  {
    username: "beate.ising",
    email: "beate.ising@posaunenwerk-rheinland.de",
    firstName: "Beate",
    lastName: "Ising",
    displayName: "Beate Ising",
    role: "OBLEUTE",
    bio: "Bezirksobfrau für Oberbergisches Land und stellvertretende Landesobfrau",
    obleuteRole: "Bezirksobfrau",
    obleuteBezirk: 9, // Bezirk 09 - Oberbergisches Land
  },
  {
    username: "klaus.groth",
    email: "klaus.groth@ekir.de",
    firstName: "Klaus",
    lastName: "Groth",
    displayName: "Klaus Groth",
    role: "OBLEUTE",
    bio: "Bezirksobmann für Wied",
    obleuteRole: "Bezirksobmann",
    obleuteBezirk: 10, // Bezirk 10 - Wied
  },
  {
    username: "jochen.conrad",
    email: "jochen.conrad@posaunenwerk-rheinland.de",
    firstName: "Jochen",
    lastName: "Conrad",
    displayName: "Jochen Conrad",
    role: "OBLEUTE",
    bio: "Bezirksobmann für An Nahe und Glan",
    obleuteRole: "Bezirksobmann",
    obleuteBezirk: 11, // Bezirk 11 - An Nahe und Glan
  },
  {
    username: "andrea.lehmann",
    email: "andrea.lehmann@posaunenwerk-rheinland.de",
    firstName: "Andrea",
    lastName: "Lehmann",
    displayName: "Andrea Lehmann",
    role: "OBLEUTE",
    bio: "Bezirksobfrau für Saarland",
    obleuteRole: "Bezirksobfrau",
    obleuteBezirk: 12, // Bezirk 12 - Saarland
  },
  {
    username: "ursula.doering",
    email: "ursula.doering@posaunenwerk-rheinland.de",
    firstName: "Ursula",
    lastName: "Doering",
    displayName: "Ursula Doering",
    role: "OBLEUTE",
    bio: "Bezirksobfrau für An Sieg und Rhein",
    obleuteRole: "Bezirksobfrau",
    obleuteBezirk: 13, // Bezirk 13 - An Sieg und Rhein
  },

  // Admin user for testing
  {
    username: "admin",
    email: "admin@posaunenwerk-rheinland.de",
    firstName: "Administrator",
    lastName: "",
    displayName: "Administrator",
    role: "ADMIN",
    bio: "System Administrator für die Website",
    obleuteRole: null,
    obleuteBezirk: null,
  },

  // Regular users for testing
  {
    username: "max.mustermann",
    email: "max.mustermann@example.com",
    firstName: "Max",
    lastName: "Mustermann",
    displayName: "Max Mustermann",
    role: "USER",
    bio: "Trompeter im Posaunenchor Essen",
    obleuteRole: null,
    obleuteBezirk: null,
  },
  {
    username: "anna.schmidt",
    email: "anna.schmidt@example.com",
    firstName: "Anna",
    lastName: "Schmidt",
    displayName: "Anna Schmidt",
    role: "USER",
    bio: "Posaunistin im Jugendposaunenchor Köln",
    obleuteRole: null,
    obleuteBezirk: null,
  },

  // ============================================================================
  // VORSTAND MEMBERS (need user accounts)
  // ============================================================================
  {
    username: "friedemann.schmidt-eggert",
    email: "landesobmann@posaunenwerk-rheinland.de",
    firstName: "Friedemann",
    lastName: "Schmidt-Eggert",
    displayName: "Friedemann Schmidt-Eggert",
    role: "ADMIN",
    bio: "Landesobmann des Posaunenwerks Rheinland",
    obleuteRole: null,
    obleuteBezirk: null,
  },
  {
    username: "dietmar.persian",
    email: "stellv.landesobmann@posaunenwerk-rheinland.de",
    firstName: "Dietmar",
    lastName: "Persian",
    displayName: "Dietmar Persian",
    role: "ADMIN",
    bio: "Stellvertretender Landesobmann des Posaunenwerks",
    obleuteRole: null,
    obleuteBezirk: null,
  },
  {
    username: "frank.beekmann",
    email: "schatzmeister@posaunenwerk-rheinland.de",
    firstName: "Frank",
    lastName: "Beekmann",
    displayName: "Frank Beekmann",
    role: "ADMIN",
    bio: "Schatzmeister des Posaunenwerks Rheinland",
    obleuteRole: null,
    obleuteBezirk: null,
  },

  // ============================================================================
  // TEAM MEMBERS (need user accounts)
  // ============================================================================
  {
    username: "heide.neuland",
    email: "heide.neuland@posaunenwerk-rheinland.de",
    firstName: "Heide",
    lastName: "Neuland-Neuhaus",
    displayName: "Heide Neuland-Neuhaus",
    role: "ADMIN",
    bio: "Content Management im Internet-Team",
    obleuteRole: null,
    obleuteBezirk: null,
  },
  {
    username: "sinika.haeusler",
    email: "info@posaunenwerk-rheinland.de",
    firstName: "Sinika",
    lastName: "Häusler",
    displayName: "Sinika Häusler",
    role: "ADMIN",
    bio: "Mitarbeiterin der Geschäftsstelle",
    obleuteRole: null,
    obleuteBezirk: null,
  },
  {
    username: "lars.lehmann",
    email: "lars.lehmann@posaunenwerk-rheinland.de",
    firstName: "Lars",
    lastName: "Lehmann",
    displayName: "Lars Lehmann",
    role: "ADMIN",
    bio: "Web-Entwicklung, Administration, Design & Content Management",
    obleuteRole: null,
    obleuteBezirk: null,
  },

  // ============================================================================
  // POSAUNENRAT MEMBERS (need user accounts)
  // ============================================================================
  {
    username: "ulrich.cyganek",
    email: "ulrich.cyganek@ekir.de",
    firstName: "Ulrich",
    lastName: "Cyganek",
    displayName: "Ulrich Cyganek",
    role: "USER",
    bio: "Landeskirchenmusikdirektor der Evangelischen Kirche im Rheinland",
    obleuteRole: null,
    obleuteBezirk: null,
  },
];
